// Hand-written TypeScript types mirroring the OpenAPI 3.1 spec shipped at
// padosoft/askmydocs-mcp-pack/resources/openapi/v1.5.json. Generated by hand
// (not via openapi-typescript codegen) because the surface is small enough
// that explicit, readable types are more maintainable than machine output.
//
// 1:1 with the OpenAPI components/schemas block. When the spec moves, this
// file moves with it.

// ============================== Common ============================== //

/**
 * Standard error envelope: `{ error: { code, message } }`. Surfaced by every
 * non-2xx response except 422 validation errors which use {@link ValidationError}.
 */
export interface ApiErrorPayload {
  error: {
    code: string;
    message: string;
  };
}

/**
 * Laravel-style validation error envelope on 422. `errors` is a map of
 * field-name → array of human-readable error strings.
 */
export interface ValidationErrorPayload {
  message?: string;
  errors?: Record<string, string[]>;
}

// ============================== Identity ============================== //

export interface HostUser {
  id: number | string;
  email?: string;
  name?: string;
  initials?: string;
  tenant_id?: string | null;
  permissions?: string[];
}

export interface HostUserEnvelope {
  data: HostUser;
  meta?: {
    tenant_id?: string | null;
  };
}

export interface HostTenant {
  id: string;
  name: string;
  primary?: boolean;
}

export interface HostApiKey {
  id: string;
  name: string;
  scopes: string[];
  last_used_at?: number | string | null;
  created_at: number | string;
  created_by?: string | null;
}

/**
 * Mint-time envelope — the `plaintext` field is surfaced exactly once.
 */
export interface HostApiKeyCreateEnvelope {
  data: HostApiKey & { plaintext: string };
}

export interface CreateApiKeyRequest {
  name: string;
  scopes: string[];
}

export interface UpdatePreferencesRequest {
  preferences: Record<string, unknown>;
}

// ============================== Servers ============================== //

export type McpTransport = 'http' | 'sse' | 'stdio';
export type McpServerStatus = 'ok' | 'warn' | 'err';

export interface McpServer {
  id: string;
  name: string;
  transport: McpTransport;
  url?: string;
  status?: McpServerStatus;
  enabled?: boolean;
  tenant?: string;
}

export interface McpServerWrite {
  name: string;
  transport: McpTransport;
  url?: string;
  enabled?: boolean;
}

export interface McpServerEnvelope {
  data: McpServer;
}

export interface McpServerPage {
  data: McpServer[];
  meta?: {
    current_page?: number;
    last_page?: number;
    per_page?: number;
    total?: number;
  };
}

export interface ServerListFilters {
  tenant?: string;
  q?: string;
  status?: string;
  transport?: string;
  enabled?: boolean;
  page?: number;
  per_page?: number;
}

// ============================== Tools ============================== //

export interface Tool {
  server_id: string;
  name: string;
  description?: string;
  /**
   * JSON-schema fragment describing the tool's input parameters. Arbitrary
   * shape — the wire schema is `additionalProperties: true`.
   */
  input_schema?: Record<string, unknown>;
}

/**
 * Tool invocation result. The body is fully arbitrary by spec — callers
 * should narrow per tool.
 */
export type ToolInvokeResult = unknown;

/**
 * Confirm-token mint response shape on 202 — the FE must POST again with
 * `{ confirm_token }` in the body to actually execute.
 */
export interface ConfirmTokenMint {
  confirm_token: string;
  /** The original request — replayed verbatim on the second call. */
  request_hash?: string;
  /** Server-set TTL in seconds — best-effort hint to the UI. */
  expires_in?: number;
  message?: string;
}

// ============================== Resources / Prompts ============================== //

export type ResourceKind = 'dir' | 'file';

export interface Resource {
  uri: string;
  name: string;
  type: ResourceKind;
  mime?: string;
  size?: number;
  parent?: string;
}

export interface ResourceContent {
  uri: string;
  name?: string;
  mime?: string;
  size?: number;
  /** Plain string or base64 for binary payloads. */
  content: string;
}

export interface ResourceContentEnvelope {
  data: ResourceContent;
}

export interface Prompt {
  name: string;
  desc?: string;
  args: Array<Record<string, unknown>>;
  preview: Array<Record<string, unknown>>;
}

// ============================== Audit ============================== //

export interface AuditRow {
  id: number | string;
  tenant_id?: string | null;
  actor?: string | null;
  mcp_server_id: string;
  mcp_server_name?: string;
  tool_name: string;
  duration_ms?: number;
  status: string;
  error_excerpt?: string | null;
  created_at?: string | null;
}

export interface AuditDetail extends AuditRow {
  request?: Record<string, unknown>;
  response?: Record<string, unknown>;
  headers?: Record<string, unknown>;
  timeline?: Array<Record<string, unknown>>;
  meta?: Record<string, unknown>;
}

export interface AuditListFilters {
  server_id?: string;
  tool_name?: string;
  status?: string;
  from?: string;
  to?: string;
  per_page?: number;
}

// ============================== Resilience ============================== //

export type BreakerStateName = 'closed' | 'open' | 'half_open';

export interface BreakerState {
  key: string;
  server_id?: string;
  tool_name?: string;
  state: BreakerStateName;
  failures?: number;
  opened_at?: number | string | null;
}

// ============================== Events (SSE) ============================== //

export interface AuditEvent {
  id: number | string;
  ts?: number | string;
  server_id?: string;
  tool?: string;
  status?: number | string;
  dur?: number;
  actor?: string;
}

// ============================== Wrapped responses ============================== //

/** Generic `{ data: T[] }` envelope used by every list endpoint. */
export interface DataEnvelope<T> {
  data: T;
}

export type ListEnvelope<T> = DataEnvelope<T[]>;
