<?php

declare(strict_types=1);

namespace Padosoft\AskMyDocsMcpPackAdmin;

use Illuminate\Support\Facades\Route;
use Illuminate\Support\ServiceProvider;

class McpPackAdminServiceProvider extends ServiceProvider
{
    public function register(): void
    {
        $this->mergeConfigFrom(
            __DIR__.'/../config/mcp-pack-admin.php',
            'mcp-pack-admin'
        );
    }

    public function boot(): void
    {
        $this->loadViewsFrom(__DIR__.'/../resources/views', 'mcp-pack-admin');
        $this->loadRoutesFrom(__DIR__.'/../routes/web.php');

        if ($this->app->runningInConsole()) {
            $this->publishes([
                __DIR__.'/../config/mcp-pack-admin.php' => config_path('mcp-pack-admin.php'),
            ], 'mcp-pack-admin-config');

            $this->publishes([
                __DIR__.'/../resources/views' => resource_path('views/vendor/mcp-pack-admin'),
            ], 'mcp-pack-admin-views');

            // mcp-pack-admin-assets tag publishes the *built* Vite bundle
            // (`.vite/manifest.json` + hashed `assets/*.{js,css}`), not the
            // pre-build source under `resources/js`. Publishing source would
            // skip Vite, drop the manifest, and force consumers to re-bundle.
            //
            // The directory is generated by `npm run build` (output configured
            // in `vite.config.ts` to `public/vendor/mcp-pack-admin`) and is
            // git-ignored during development. Release tarballs include it via
            // a CI build-and-bundle step before `composer archive`. The guard
            // keeps `php artisan vendor:publish` honest before that point: if
            // the built tree is absent, the tag is simply not registered
            // instead of mapping a non-existent source.
            $builtAssetsPath = __DIR__.'/../public/vendor/mcp-pack-admin';
            if (is_dir($builtAssetsPath)) {
                $this->publishes([
                    $builtAssetsPath => public_path('vendor/mcp-pack-admin'),
                ], 'mcp-pack-admin-assets');
            }
        }
    }
}
